
#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 7
#define TAPPING_TERM 200

// OLED settings
#define OLED_TIMEOUT    80000
// #define OLED_DISPLAY_128x64
#define OLED_BRIGHTNESS 90
#define OLED_DISPLAY_WIDTH 128
#define OLED_DISPLAY_HEIGHT 32
