MCU = RP2040
BOOTLOADER = rp2040
CONVERT_TO = promicro_rp2040

# TRI_LAYER_ENABLE = yes
VIA_ENABLE = yes
ENCODER_MAP_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_ENABLE = no
# TAP_DANCE_ENABLE = yes
OLED_ENABLE = yes
LTO_ENABLE = yes
