MCU = RP2040
BOOTLOADER = rp2040
CONVERT_TO = promicro_rp2040

TRI_LAYER_ENABLE = no
VIA_ENABLE = yes
ENCODER_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_ENABLE = no
TAP_DANCE_ENABLE = yes
WPM_ENABLE = no
# https://docs.qmk.fm/#/feature_oled_driver?id=basic-configuration
OLED_ENABLE  = yes
LTO_ENABLE = yes
